---
abstract: 'Import a set of modules into the calling module'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Carp: '0'
  Module::Build: '0.28'
  Test::Compile: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Import-Base
requires:
  Import::Into: '1.002000'
  Module::Runtime: '0'
  mro: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/preaction/Import-Base/issues
  homepage: https://github.com/preaction/Import-Base
  repository: https://github.com/preaction/Import-Base.git
version: '0.010'
x_authority: cpan:PREACTION
